name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      PORT: ${{ secrets.PORT }}
      NAMEDB: ${{ secrets.NAMEDB }}
      USERDB: ${{ secrets.USERDB }}
      PASSDB: ${{ secrets.PASSDB }}
      LOCALHOSTDB: ${{ secrets.LOCALHOSTDB }}
      VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug environment variables
        run: |
          echo "EMAIL_USER: $EMAIL_USER"
          echo "EMAIL_PASS: $EMAIL_PASS"
          echo "PORT: $PORT"
          echo "NAMEDB: $NAMEDB"
          echo "USERDB: $USERDB"
          echo "PASSDB: $PASSDB"
          echo "LOCALHOSTDB: $LOCALHOSTDB"
          echo "VITE_SERVER_URL: $VITE_SERVER_URL"

      - name: Run Node.js script that uses secrets
        run: |
          npm install
          echo "Running Node.js script"
          node deploy.js
